[project]
name = "pythonproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dlt[duckdb,postgres,sql-database]>=1.15.0",
    "duckdb>=1.3.2",
    "pip>=25.2",
    "psycopg2-binary>=2.9.10",
]
