[runtime]
log_level="WARNING"
dlthub_telemetry = true


[destination.filesystem]
bucket_url = "./data/json_export_sql"
layout = "{table_name}/{load_id}.{file_id}.{ext}"

[sql_filesystem_pipeline.pipeline]
loader_file_format = "jsonl"