[sources.sql_database.credentials]
drivername = "postgresql+psycopg2"
host = "localhost"
port = 5432
database = "testdb"
username = "testuser"
password = "testpass"

[destination.duckdb.credentials]
database = "dlt_database.duckdb"


[destination.filesystem]
bucket_url = "./data/json_export_sql"
layout = "{table_name}/{load_id}.{file_id}.{ext}"

[sql_filesystem_pipeline.normalize.data_writer]
disable_compression = true

[sql_filesystem_pipeline.pipeline]
loader_file_format = "jsonl"
