[sources.sql_database.credentials]
drivername = "postgresql+psycopg2"
host = "localhost"
port = 5432
database = "testdb"
username = "testuser"
password = "testpass"

[destination.duckdb.credentials]
database = "dlt_database.duckdb"